/**
 * The famous places we show on the Location map.
 *
 * Each entry needs a name, coordinates, a district, a short description and a
 * photograph from /public/images/places/. To add a place, copy any block below,
 * change the values, and drop a matching photo into that folder — nothing else
 * in the code needs to change.
 */

export const CATEGORIES = {
  heritage: { label: 'Heritage & ruins', color: '#B4741F' },
  nature: { label: 'Hills & nature', color: '#1F7A45' },
  beach: { label: 'Beaches & coast', color: '#1F7F92' },
  wildlife: { label: 'Wildlife parks', color: '#7A5C1F' },
  city: { label: 'Cities & towns', color: '#5A4A7A' },
}

export const PLACES = [
  // ---------------------------------------------------------------- heritage
  {
    id: 'sigiriya',
    name: 'Sigiriya Rock Fortress',
    district: 'Matale',
    category: 'heritage',
    lat: 7.9570,
    lng: 80.7603,
    image: '/images/places/sigiriya.jpg',
    blurb: 'A fifth century palace on top of a 200 metre rock, with frescoes and a lion-paw staircase.',
    tip: 'Start climbing by 7am — the steps get hot and crowded fast.',
  },
  {
    id: 'dambulla',
    name: 'Dambulla Cave Temple',
    district: 'Matale',
    category: 'heritage',
    lat: 7.8567,
    lng: 80.6492,
    image: '/images/places/dambulla.jpg',
    blurb: 'Five caves packed with 150 Buddha statues and ceilings painted end to end.',
    tip: 'Twenty minutes from Sigiriya, so most guests do both in one day.',
  },
  {
    id: 'polonnaruwa',
    name: 'Polonnaruwa Ancient City',
    district: 'Polonnaruwa',
    category: 'heritage',
    lat: 7.9403,
    lng: 81.0188,
    image: '/images/places/polonnaruwa.jpg',
    blurb: 'The island\u2019s second capital: stone Buddhas, royal baths and a well preserved quadrangle.',
    tip: 'Best seen by bicycle — the ruins are spread over a few kilometres.',
  },
  {
    id: 'anuradhapura',
    name: 'Anuradhapura',
    district: 'Anuradhapura',
    category: 'heritage',
    lat: 8.3114,
    lng: 80.4037,
    image: '/images/places/anuradhapura.jpg',
    blurb: 'The oldest capital, home to the sacred Bo tree grown from a cutting brought in 288 BC.',
    tip: 'Wear white and cover shoulders and knees; this is a living pilgrimage site.',
  },
  {
    id: 'galle-fort',
    name: 'Galle Fort',
    district: 'Galle',
    category: 'heritage',
    lat: 6.0261,
    lng: 80.2168,
    image: '/images/places/galle-fort.jpg',
    blurb: 'A Dutch walled town of cafes, boutiques and ramparts you can walk right around.',
    tip: 'Walk the walls at sunset, then eat inside the fort.',
  },
  {
    id: 'adams-peak',
    name: 'Adam\u2019s Peak (Sri Pada)',
    district: 'Ratnapura',
    category: 'heritage',
    lat: 6.8096,
    lng: 80.4994,
    image: '/images/places/adams-peak.jpg',
    blurb: 'A night climb of 5,500 steps to a sacred footprint, timed to reach the top for sunrise.',
    tip: 'Pilgrimage season runs December to May. Start around 2am.',
  },

  // ------------------------------------------------------------------ nature
  {
    id: 'ella',
    name: 'Ella',
    district: 'Badulla',
    category: 'nature',
    lat: 6.8667,
    lng: 81.0466,
    image: '/images/places/ella.jpg',
    blurb: 'A small hill town with Little Adam\u2019s Peak, Ella Rock and a valley view from every cafe.',
    tip: 'Two nights is better than one — the walks are worth a full day.',
  },
  {
    id: 'nine-arch-bridge',
    name: 'Nine Arch Bridge',
    district: 'Badulla',
    category: 'nature',
    lat: 6.8767,
    lng: 81.0602,
    image: '/images/places/nine-arch-bridge.jpg',
    blurb: 'A colonial railway viaduct curving through the jungle, best when a blue train crosses it.',
    tip: 'Ask us for the day\u2019s train times so you are there at the right moment.',
  },
  {
    id: 'nuwara-eliya',
    name: 'Nuwara Eliya',
    district: 'Nuwara Eliya',
    category: 'nature',
    lat: 6.9497,
    lng: 80.7891,
    image: '/images/places/nuwara-eliya.jpg',
    blurb: 'Tea estates, cool air and colonial bungalows — the locals call it Little England.',
    tip: 'Bring a jacket. Nights here drop to 10°C.',
  },
  {
    id: 'haputale',
    name: 'Haputale & Lipton\u2019s Seat',
    district: 'Badulla',
    category: 'nature',
    lat: 6.7679,
    lng: 80.9515,
    image: '/images/places/haputale.jpg',
    blurb: 'A ridge town where the view drops away on both sides, above miles of tea.',
    tip: 'Lipton\u2019s Seat clouds over by 10am — go at dawn.',
  },
  {
    id: 'ravana-falls',
    name: 'Ravana Falls',
    district: 'Badulla',
    category: 'nature',
    lat: 6.8489,
    lng: 81.0459,
    image: '/images/places/ravana-falls.jpg',
    blurb: 'A wide 25 metre waterfall right beside the Ella–Wellawaya road.',
    tip: 'Fullest just after the monsoon; a trickle in the dry months.',
  },

  // ----------------------------------------------------------------- beaches
  {
    id: 'mirissa',
    name: 'Mirissa',
    district: 'Matara',
    category: 'beach',
    lat: 5.9483,
    lng: 80.4589,
    image: '/images/places/mirissa.jpg',
    blurb: 'A crescent bay of palms and beach bars, and the launch point for blue whale trips.',
    tip: 'Whale season is November to April. Boats leave at 6am.',
  },
  {
    id: 'unawatuna',
    name: 'Unawatuna',
    district: 'Galle',
    category: 'beach',
    lat: 6.0094,
    lng: 80.2494,
    image: '/images/places/unawatuna.jpg',
    blurb: 'A sheltered bay with calm swimming, ten minutes from Galle Fort.',
    tip: 'The calmest water on the south coast for families.',
  },
  {
    id: 'hikkaduwa',
    name: 'Hikkaduwa',
    district: 'Galle',
    category: 'beach',
    lat: 6.1395,
    lng: 80.1063,
    image: '/images/places/hikkaduwa.jpg',
    blurb: 'Coral sanctuary, sea turtles close to shore and a reliable beginner surf break.',
    tip: 'Glass bottom boats run all morning from the main beach.',
  },
  {
    id: 'arugam-bay',
    name: 'Arugam Bay',
    district: 'Ampara',
    category: 'beach',
    lat: 6.8402,
    lng: 81.8360,
    image: '/images/places/arugam-bay.jpg',
    blurb: 'The east coast surf capital — a long right-hand point break and a slow village pace.',
    tip: 'Season is May to September, the opposite of the south coast.',
  },
  {
    id: 'trincomalee',
    name: 'Trincomalee',
    district: 'Trincomalee',
    category: 'beach',
    lat: 8.5874,
    lng: 81.2152,
    image: '/images/places/trincomalee.jpg',
    blurb: 'One of the world\u2019s finest natural harbours, with Nilaveli and Uppuveli beaches nearby.',
    tip: 'Best May to September when the south coast is rough.',
  },
  {
    id: 'negombo',
    name: 'Negombo',
    district: 'Gampaha',
    category: 'beach',
    lat: 7.2083,
    lng: 79.8358,
    image: '/images/places/negombo.jpg',
    blurb: 'A fishing town and lagoon twenty minutes from the airport.',
    tip: 'The sensible first or last night if your flight is awkward.',
  },

  // ---------------------------------------------------------------- wildlife
  {
    id: 'yala',
    name: 'Yala National Park',
    district: 'Hambantota',
    category: 'wildlife',
    lat: 6.3728,
    lng: 81.5199,
    image: '/images/places/yala.jpg',
    blurb: 'The highest density of leopards in the world, plus elephants, sloth bears and crocodiles.',
    tip: 'Book the 5am block. Yala usually closes in September.',
  },
  {
    id: 'udawalawe',
    name: 'Udawalawe National Park',
    district: 'Ratnapura',
    category: 'wildlife',
    lat: 6.4750,
    lng: 80.8983,
    image: '/images/places/udawalawe.jpg',
    blurb: 'Elephants all year round in open grassland — the surest sighting on the island.',
    tip: 'The elephant transit home feeds orphaned calves at 6am, 9am, noon and 3pm.',
  },
  {
    id: 'minneriya',
    name: 'Minneriya National Park',
    district: 'Polonnaruwa',
    category: 'wildlife',
    lat: 8.0286,
    lng: 80.8975,
    image: '/images/places/minneriya.jpg',
    blurb: 'Home of The Gathering, when hundreds of elephants meet at the shrinking reservoir.',
    tip: 'August and September are the peak. We check which park the herds moved to.',
  },
  {
    id: 'kaudulla',
    name: 'Kaudulla National Park',
    district: 'Polonnaruwa',
    category: 'wildlife',
    lat: 8.1667,
    lng: 80.9333,
    image: '/images/places/kaudulla.jpg',
    blurb: 'Minneriya\u2019s quieter neighbour, and often the better choice when the herds move north.',
    tip: 'Fewer jeeps here than Minneriya for the same elephants.',
  },
  {
    id: 'wilpattu',
    name: 'Wilpattu National Park',
    district: 'Puttalam',
    category: 'wildlife',
    lat: 8.4500,
    lng: 80.0500,
    image: '/images/places/wilpattu.jpg',
    blurb: 'The largest and wildest park, built around natural lakes called villus.',
    tip: 'Far less busy than Yala, with a real chance of leopards.',
  },

  // ------------------------------------------------------------------ cities
  {
    id: 'kandy',
    name: 'Kandy',
    district: 'Kandy',
    category: 'city',
    lat: 7.2906,
    lng: 80.6337,
    image: '/images/places/kandy.jpg',
    blurb: 'The hill capital, its lake, and the Temple of the Sacred Tooth Relic.',
    tip: 'Evening puja at the temple is the moment to be there.',
  },
  {
    id: 'colombo',
    name: 'Colombo',
    district: 'Colombo',
    category: 'city',
    lat: 6.9271,
    lng: 79.8612,
    image: '/images/places/colombo.jpg',
    blurb: 'The capital: Galle Face Green, Pettah market, colonial arcades and rooftop bars.',
    tip: 'One full day is enough before heading inland.',
  },
]

/** Places grouped by their category key, in the order the categories are declared. */
export function placesByCategory() {
  return Object.keys(CATEGORIES).map((key) => ({
    key,
    ...CATEGORIES[key],
    places: PLACES.filter((p) => p.category === key),
  }))
}